/*
	This work has been done all together, so we didn't split it.
*/

CREATE TABLE  "ADMIN"  
   (    "ADMIN_SSN" NUMBER NOT NULL ENABLE,  
	     CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ADMIN_SSN") ENABLE, 
	       CONSTRAINT "ADMIN_FK" FOREIGN KEY ("ADMIN_SSN") 
	      REFERENCES  "EMPLOYEES" ("EMPLOYEE_SSN") ON DELETE CASCADE ENABLE 
	   ) ; 



CREATE TABLE  "ALBUM"  
   (    "ALBUM_REFERENCENUMBER" NUMBER NOT NULL ENABLE,  
	    "ALBUM_GENRE" VARCHAR2(32) NOT NULL ENABLE,  
	    "ALLBUM_ISPHYSICAL" VARCHAR2(32)  DEFAULT 'YES',  
	    "ALBUM_YEAR" DATE,  
	    "ALBUM_MONTH" DATE,  
	     CONSTRAINT "ALBUM_PK" PRIMARY KEY ("ALBUM_REFERENCENUMBER") ENABLE 
	   ) ; 



CREATE TABLE  "ALBUMTRACKARTIST"  
   (    "ALBUMTRACKARTIST_ARTISTICNAME" VARCHAR2(32),  
	    "ALBUMTRACKARTIST_TRACKREFNUM" NUMBER,  
	    "ALBUMTRACKARTIST_ALBUMREFNUM" NUMBER,  
	     CONSTRAINT "ABUMTRACKARTIST_CON" PRIMARY KEY ("ALBUMTRACKARTIST_ARTISTICNAME", "ALBUMTRACKARTIST_TRACKREFNUM", "ALBUMTRACKARTIST_ALBUMREFNUM") ENABLE, 
	       CONSTRAINT "ABUMTRACKARTIST_FK" FOREIGN KEY ("ALBUMTRACKARTIST_ARTISTICNAME") 
	      REFERENCES  "ARTISTS" ("ARTIST_ARTISTICNAME") ENABLE, 
	CONSTRAINT "ABUMTRACKARTIST_FK2" FOREIGN KEY ("ALBUMTRACKARTIST_TRACKREFNUM") 
	      REFERENCES  "TRACKS" ("TRACKS_REFERENCENUMBER") ENABLE, 
	CONSTRAINT "ABUMTRACKARTIST_FK3" FOREIGN KEY ("ALBUMTRACKARTIST_ALBUMREFNUM") 
	      REFERENCES  "ALBUM" ("ALBUM_REFERENCENUMBER") ENABLE 
	   ) ; 



CREATE TABLE  "ALBUM_AUTHORS"  
   (    "ALBUM_AUTHORS_REFERENCENUMBER" NUMBER NOT NULL ENABLE,  
	    "ALBUM_AUTHORS_FIRSTNAME" VARCHAR2(32) NOT NULL ENABLE,  
	    "ALBUM_AUTHORS_SECONDNAME" VARCHAR2(32) NOT NULL ENABLE,  
	     CONSTRAINT "ALBUM_AUTHORS_CON" PRIMARY KEY ("ALBUM_AUTHORS_REFERENCENUMBER", "ALBUM_AUTHORS_FIRSTNAME", "ALBUM_AUTHORS_SECONDNAME") ENABLE, 
	       CONSTRAINT "ALBUM_AUTHORS_FK" FOREIGN KEY ("ALBUM_AUTHORS_REFERENCENUMBER") 
	      REFERENCES  "ALBUM" ("ALBUM_REFERENCENUMBER") ON DELETE CASCADE ENABLE 
	   ) ; 



CREATE TABLE  "ARTISTS"  
   (    "ARTIST_ARTISTICNAME" VARCHAR2(32) NOT NULL ENABLE,  
	    "ARTIST_FIRSTNAME" VARCHAR2(32) NOT NULL ENABLE,  
	    "ARTIST_SECONDNAME" VARCHAR2(32) NOT NULL ENABLE,  
	    "ARTIST_NATIONALITYE" VARCHAR2(32) NOT NULL ENABLE, 
	    "ARTIST_BIRTHDAY" DATE,  
	    "ARTIST_AGE" NUMBER,  
	    "ARTIST_AGEOFEXPERIENCE" NUMBER,  
	    "ARTIST_DEBUTDATE" DATE,  
	    "ARTIST_TOTALSALES" NUMBER DEFAULT 0,  
	    "ARTIST_ROYALTIES" NUMBER DEFAULT 0, 
	    "ARTIST_AWARDS" NUMBER DEFAULT 0, 
	    "ARTIST_ISALIVE" VARCHAR2(32) DEFAULT 'YES', 
	     CONSTRAINT "PK_ARTIST_ARTISTICNAME" PRIMARY KEY ("ARTIST_ARTISTICNAME") ENABLE, 
	     CONSTRAINT "CK_ARTIST_TOTALSALES" CHECK("ARTIST_TOTALSALES">=0) ENABLE, 
	     CONSTRAINT "CK_ARTIST_ISALIVE" CHECK("ARTIST_ISALIVE" LIKE '[SI, NO]') ENABLE, 
	     CONSTRAINT "ARTIST_ROYALTIES" CHECK("ARTIST_ROYALTIES">=0) ENABLE, 
	     CONSTRAINT "ARTIST_AWARDS" CHECK("ARTIST_AWARDS">=0) ENABLE 
	   ) ; 


CREATE TABLE  "ARTIST_LABELSWORK"  
   (    "ARTIST_LABELSWORK_ARTISTICNAME" VARCHAR2(32) NOT NULL ENABLE,  
	    "ARTIST_LABELSWORK_LABELSNAME" VARCHAR2(32) NOT NULL ENABLE,  
	     CONSTRAINT "ARTIST_LABELSWORK_CON" PRIMARY KEY ("ARTIST_LABELSWORK_ARTISTICNAME", "ARTIST_LABELSWORK_LABELSNAME") ENABLE, 
	       CONSTRAINT "ARTIST_LABELSWORK_FK" FOREIGN KEY ("ARTIST_LABELSWORK_ARTISTICNAME") 
	      REFERENCES  "ARTISTS" ("ARTIST_ARTISTICNAME") ENABLE 
	   ) ; 



CREATE TABLE  "ARTREC"  
   (    "ARTREC_CIFRECORDLABEL" VARCHAR2(50) NOT NULL ENABLE,  
	    "ARTREC_ARTISTICNAME" VARCHAR2(50) NOT NULL ENABLE,  
	     CONSTRAINT "ARTREC_PK" PRIMARY KEY ("ARTREC_CIFRECORDLABEL", "ARTREC_ARTISTICNAME") ENABLE, 
	      CONSTRAINT "ARTREC_FK" FOREIGN KEY ("ARTREC_CIFRECORDLABEL") 
	      REFERENCES  "RECORDLABEL" ("RECORDLABEL_CIF") ENABLE, 
	CONSTRAINT "ARTREC_FK2" FOREIGN KEY ("ARTREC_ARTISTICNAME") 
	      REFERENCES  "ARTISTS" ("ARTIST_ARTISTICNAME") ENABLE 
	   ) ; 


CREATE TABLE  "BILLINGINFORMATION"  
   (    "BILLINGINFORMATION_TYPEACCOUNT" VARCHAR2(32) NOT NULL ENABLE,  
	    "BILLINGINFORMATION_NUMBERACCNT" NUMBER NOT NULL ENABLE,  
	    "BILLINGINFORMATION_USERUSERNAM" VARCHAR2(32) NOT NULL ENABLE,  
	     CONSTRAINT "BILLINGINFORMATION_CON" PRIMARY KEY ("BILLINGINFORMATION_TYPEACCOUNT", "BILLINGINFORMATION_NUMBERACCNT", "BILLINGINFORMATION_USERUSERNAM") ENABLE, 
	       CONSTRAINT "BILLINGINFORMATION_FK2" FOREIGN KEY ("BILLINGINFORMATION_USERUSERNAM") 
	      REFERENCES  "USERS" ("USERS_USERNAME") ENABLE 
	   ) ; 



CREATE TABLE  "COUPONS"  
   (    "COUPONS_CODE" VARCHAR2(64) NOT NULL ENABLE,  
	    "COUPONS_EXPIRATION" DATE,  
	    "COUPONS_DISCOUNT" NUMBER NOT NULL ENABLE,  
	    "COUPONS_COUPONFORMAT" VARCHAR2(64) NOT NULL ENABLE,  
	    "COUPONS_STARTDATE" DATE NOT NULL ENABLE,  
	     CONSTRAINT "COUPONS_PK" PRIMARY KEY ("COUPONS_CODE") ENABLE 
	   ) ; 


CREATE TABLE  "COUPON_NAMES"  
   (    "COUPON_NAMES_CODE" VARCHAR2(32) NOT NULL ENABLE,  
	    "COUPON_NAMES_NAME" VARCHAR2(32) DEFAULT 'NO NAME' NOT NULL ENABLE,  
	     CONSTRAINT "COUPON_NAMES_CON" PRIMARY KEY ("COUPON_NAMES_CODE", "COUPON_NAMES_NAME") ENABLE, 
	       CONSTRAINT "COUPON_NAMES_FK" FOREIGN KEY ("COUPON_NAMES_CODE") 
	      REFERENCES  "COUPONS" ("COUPONS_CODE") ENABLE 
	   ) ; 




CREATE TABLE  "DEVELOPERS"  
   (    "DEVELOPERS_SSN" NUMBER NOT NULL ENABLE,  
	    "DEVELOPERS_PROGRAMMINGLENGUAJE" VARCHAR2(33),  
	     CONSTRAINT "DEVELOPERS_PK" PRIMARY KEY ("DEVELOPERS_SSN") ENABLE, 
	       CONSTRAINT "DEVELOPERS_FK" FOREIGN KEY ("DEVELOPERS_SSN") 
	      REFERENCES  "EMPLOYEES" ("EMPLOYEE_SSN") ON DELETE CASCADE ENABLE 
	   ) ; 


CREATE TABLE  "DISTRADMIN"  
   (    "CIFDISTRIBUTOR" VARCHAR2(50) NOT NULL ENABLE,  
	    "SSNADMIN" NUMBER NOT NULL ENABLE,  
	     CONSTRAINT "DISTRADMIN_PK" PRIMARY KEY ("SSNADMIN", "CIFDISTRIBUTOR") ENABLE, 
	       CONSTRAINT "DISTRADMIN_FK" FOREIGN KEY ("CIFDISTRIBUTOR") 
	      REFERENCES  "DISTRIBUTOR" ("DISTRIBUTOR_CIF") ENABLE, 
	CONSTRAINT "DISTRADMIN_FK2" FOREIGN KEY ("SSNADMIN") 
	      REFERENCES  "ADMIN" ("ADMIN_SSN") ENABLE 
	   ) ; 



CREATE TABLE  "DISTRIBUTOR"  
   (    "DISTRIBUTOR_CIF" VARCHAR2(32) NOT NULL ENABLE,  
	    "DISTRIBUTOR_COMPANYNAME" VARCHAR2(64) NOT NULL ENABLE,  
	    "DISTRIBUTOR_CENTRALOFFICES" VARCHAR2(32),  
	    "DISTRIBUTOR_NATIONALITY" VARCHAR2(32) NOT NULL ENABLE,  
	     CONSTRAINT "DISTRIBUTOR_PK" PRIMARY KEY ("DISTRIBUTOR_CIF") ENABLE,  
	     CONSTRAINT "DISTRIBUTOR_UK1" UNIQUE ("DISTRIBUTOR_COMPANYNAME") ENABLE 
	   ) ; 


CREATE TABLE  "EMPADDRESS"  
   (    "EMPADRESS_SSN" NUMBER NOT NULL ENABLE,  
	    "EMPADRESS_CITY" VARCHAR2(69),  
	    "EMPADRESS_STREET" VARCHAR2(69),  
	     CONSTRAINT "EMPADDRESS_PK" PRIMARY KEY ("EMPADRESS_SSN") ENABLE, 
	       CONSTRAINT "EMPADDRESS_FK" FOREIGN KEY ("EMPADRESS_SSN") 
	      REFERENCES  "EMPLOYEES" ("EMPLOYEE_SSN") ON DELETE CASCADE ENABLE 
	   ) ; 




CREATE TABLE  "PAYROLL"  
   (    "PAYROLL_ID" NUMBER NOT NULL ENABLE,  
	    "PAYROLL_BONUS" NUMBER,  
	     CONSTRAINT "PAYROLL_PK" PRIMARY KEY ("PAYROLL_ID") ENABLE 
	   ) ; 


CREATE TABLE  "EMPLOYEES"  
   (    "EMPLOYEE_SSN" NUMBER(*,0),  
	    "EMPLOYEES_WORKINGYEARS" NUMBER(*,0) DEFAULT 0,  
	    "EMPLOYEES_HIRINGDATE" DATE NOT NULL ENABLE,  
	    "EMPLOYEES_CITY" VARCHAR2(32),  
	    "EMPLOYEES_STREET" VARCHAR2(32),  
	    "EMPLOYEES_ZIP" VARCHAR2(32),  
	    "EMPLOYEES_PHONE" NUMBER,  
	    "EMPLOYEES_PAYROLLID" NUMBER,  
	    "EMPLOYEES_ALLOWANCE" VARCHAR2(32) NOT NULL ENABLE,  
	    "EMPLOYEES_BLOODGROUP" VARCHAR2(32),  
	    "EMPLOYEES_CIVILSTATUS" VARCHAR2(32),  
	    "EMPLOYEES_CATEGORY" VARCHAR2(2) NOT NULL ENABLE,  
	     CONSTRAINT "EMPLOYEESSN" PRIMARY KEY ("EMPLOYEE_SSN") ENABLE, 
	     CONSTRAINT "CK_EMPLOYEES_WORKINGYEARS" CHECK ("EMPLOYEES_WORKINGYEARS">=0) ENABLE, 
	     CONSTRAINT "CK_EMPLOYEES_CATEGORY" CHECK  ("EMPLOYEES_CATEGORY" LIKE '[DEVELOPER, MANAGER, ADMIN]') ENABLE, 
	     CONSTRAINT "CK_EMPLOYEES_CIVILSTATUS" CHECK  ("EMPLOYEES_CIVILSTATUS" LIKE '[SOLTERO, CASADO, VIUDO]') ENABLE, 
	     CONSTRAINT "CK_EMPLOYEES_PHONE" CHECK  ("EMPLOYEES_PHONE" LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') ENABLE, 
	     CONSTRAINT "EMPLOYEESL_FK" FOREIGN KEY ("EMPLOYEES_PAYROLLID") 
	      REFERENCES  "PAYROLL" ("PAYROLL_ID") ENABLE 



	   ) ; 


CREATE TABLE  "MANAGADMIN"  
   (    "MANAGADMIN_PERSONALREALTION" VARCHAR2(50),  
	    "MANAGADMIN_SSNADMIN" NUMBER,  
	    "MANAGADMIN_SSNMAN" NUMBER,  
	     CONSTRAINT "MANAGADMIN_PK" PRIMARY KEY ("MANAGADMIN_SSNADMIN", "MANAGADMIN_SSNMAN") ENABLE, 
	       CONSTRAINT "MANAGADMIN_FK" FOREIGN KEY ("MANAGADMIN_SSNADMIN") 
	      REFERENCES  "ADMIN" ("ADMIN_SSN") ON DELETE CASCADE ENABLE, 
	CONSTRAINT "MANAGADMIN_FK2" FOREIGN KEY ("MANAGADMIN_SSNMAN") 
	      REFERENCES  "MANAGERS" ("MANAGERS_SSN") ON DELETE CASCADE ENABLE 
	   ) ; 


CREATE TABLE  "MANAGDEV"  
   (    "MANAGDEV_PERSONALREALITON" VARCHAR2(50),  
	    "MANAGDEV_SSNDEV" NUMBER,  
	    "MANAGDEV_SSNMAN" NUMBER,  
	     CONSTRAINT "MANAGDEV_PK" PRIMARY KEY ("MANAGDEV_SSNDEV", "MANAGDEV_SSNMAN") ENABLE, 
	       CONSTRAINT "MANAGDEV_FK" FOREIGN KEY ("MANAGDEV_SSNDEV") 
	      REFERENCES  "DEVELOPERS" ("DEVELOPERS_SSN") ON DELETE CASCADE ENABLE, 
	CONSTRAINT "MANAGDEV_FK2" FOREIGN KEY ("MANAGDEV_SSNMAN") 
	      REFERENCES  "MANAGERS" ("MANAGERS_SSN") ON DELETE CASCADE ENABLE 
	   ) ; 



CREATE TABLE  "MANAGERS"  
   (    "MANAGERS_SSN" NUMBER NOT NULL ENABLE,  
	     CONSTRAINT "MANAGERS_PK" PRIMARY KEY ("MANAGERS_SSN") ENABLE, 
	       CONSTRAINT "MANAGERS_FK" FOREIGN KEY ("MANAGERS_SSN") 
	      REFERENCES  "EMPLOYEES" ("EMPLOYEE_SSN") ON DELETE CASCADE ENABLE 
	   ) ; 



CREATE TABLE  "PAYMENT"  
   (    "PAYMENT_ID" VARCHAR2(64) NOT NULL ENABLE,  
	    "PAYMENT_USERSFULLNAME" VARCHAR2(64) NOT NULL ENABLE,  
	    "PAYMENT_YEAR" NUMBER NOT NULL ENABLE,  
	    "PAYMENT_MONTH" NUMBER NOT NULL ENABLE,  
	    "PAYMENT_DAY" NUMBER NOT NULL ENABLE,  
	    "PAYMENT_HOUR" NUMBER NOT NULL ENABLE,  
	     CONSTRAINT "PAYMENT_PK" PRIMARY KEY ("PAYMENT_ID") ENABLE,  
	     CONSTRAINT "PAYMENT_UK1" UNIQUE ("PAYMENT_USERSFULLNAME", "PAYMENT_YEAR", "PAYMENT_MONTH", "PAYMENT_DAY", "PAYMENT_HOUR") ENABLE 
	   ) ; 



CREATE TABLE  "PLAYLIST"  
   (    "PLAYLIST_ID" VARCHAR2(32) NOT NULL ENABLE,  
	    "PLAYLIST_NAME" VARCHAR2(32) NOT NULL ENABLE,  
	    "PLAYLIST_USERUSERNAME" VARCHAR2(64) NOT NULL ENABLE,  
	     CONSTRAINT "PLAYLIST_PK" PRIMARY KEY ("PLAYLIST_ID") ENABLE,  
	     CONSTRAINT "PLAYLIST_UK1" UNIQUE ("PLAYLIST_NAME", "PLAYLIST_USERUSERNAME") ENABLE 
	   ) ; 



CREATE TABLE  "PLAYTRACK"  
   (    "PLAYTRK_TRACKNUMBEROFREFERENCE" NUMBER NOT NULL ENABLE,  
	    "PLAYTRK_PLAYLISTID" VARCHAR2(32) NOT NULL ENABLE,  
	     CONSTRAINT "PLAYTRACK_CON" PRIMARY KEY ("PLAYTRK_TRACKNUMBEROFREFERENCE", "PLAYTRK_PLAYLISTID") ENABLE, 
	       CONSTRAINT "PLAYTRACK_CONS" FOREIGN KEY ("PLAYTRK_TRACKNUMBEROFREFERENCE") 
	      REFERENCES  "TRACKS" ("TRACKS_REFERENCENUMBER") ENABLE, 
	CONSTRAINT "PLAYTRACK_CONST" FOREIGN KEY ("PLAYTRK_PLAYLISTID") 
	      REFERENCES  "PLAYLIST" ("PLAYLIST_ID") ENABLE 
	   ) ; 


CREATE TABLE  "PURCHASE_TRACKS"  
   (    "PURCHASE_TRACKS_CARTID" NUMBER NOT NULL ENABLE,  
	    "PURCHASE_TRACKS_INITIALPRICE" NUMBER NOT NULL ENABLE,  
	    "PURCHASE_TRACKS_NUMEROFTRACKS" NUMBER NOT NULL ENABLE,  
	    "PURCHASE_TRACKS_FINALPRICE" NUMBER NOT NULL ENABLE,  
	    "PURCHASE_TRACKS_ISBOUGHTBYADS" VARCHAR2(64),  
	    "PURCHASE_TRACKS_COUPONCODE" VARCHAR2(64),  
	    "PURCHASE_TRACKS_PAYMENTID" VARCHAR2(64) NOT NULL ENABLE,  
	     CONSTRAINT "PURCHASE_TRACKS_PK" PRIMARY KEY ("PURCHASE_TRACKS_CARTID") ENABLE, 
	       CONSTRAINT "PURCHASE_TRACKS_CON" FOREIGN KEY ("PURCHASE_TRACKS_COUPONCODE") 
	      REFERENCES  "COUPONS" ("COUPONS_CODE") ON DELETE CASCADE ENABLE, 
	CONSTRAINT "PURCHASE_TRACKS_CONS" FOREIGN KEY ("PURCHASE_TRACKS_PAYMENTID") 
	      REFERENCES  "PAYMENT" ("PAYMENT_ID") ENABLE 
	   ) ; 




CREATE TABLE  "RECORDDISTR"  
   (    "RECORDDISTR_CIFDISTRIBUTOR" VARCHAR2(50) NOT NULL ENABLE,  
	    "RECORDDISTR_CIFRECORDLABEL" VARCHAR2(50) NOT NULL ENABLE,  
	     CONSTRAINT "RECORDDISTR_PK" PRIMARY KEY ("RECORDDISTR_CIFDISTRIBUTOR", "RECORDDISTR_CIFRECORDLABEL") ENABLE, 
	       CONSTRAINT "RECORDDISTR_FK" FOREIGN KEY ("RECORDDISTR_CIFDISTRIBUTOR") 
	      REFERENCES  "DISTRIBUTOR" ("DISTRIBUTOR_CIF") ENABLE, 
	       CONSTRAINT "RECORDDISTR_FK2" FOREIGN KEY ("RECORDDISTR_CIFRECORDLABEL") 
	      REFERENCES  "RECORDLABEL" ("RECORDLABEL_CIF") ENABLE 
	   ) ; 


CREATE TABLE  "RECORDLABEL"  
   (    "RECORDLABEL_CIF" VARCHAR2(50) NOT NULL ENABLE,  
	    "RECORDLABEL_BRANDNAME" VARCHAR2(50),  
	    "RECORDLABEL_NUMBEROFEMPLOYEES" NUMBER,  
	    "RECORDLABEL_STOCKMARKETVALUE" NUMBER,  
	     CONSTRAINT "RECORDLABEL_PK" PRIMARY KEY ("RECORDLABEL_CIF") ENABLE,  
	     CONSTRAINT "RECORDLABEL_UK1" UNIQUE ("RECORDLABEL_BRANDNAME") ENABLE 
	   ) ;             



CREATE TABLE  "TRACKS"  
   (    "TRACKS_REFERENCENUMBER" NUMBER NOT NULL ENABLE,  
	    "TRACKS_BPM" NUMBER,  
	     CONSTRAINT "TRACKS_PK" PRIMARY KEY ("TRACKS_REFERENCENUMBER") ENABLE 
	   ) ; 
             


CREATE TABLE  "USEREMAIL"  
   (    "USEREMAIL_EMAILACCOUNT" VARCHAR2(32) NOT NULL ENABLE,  
	    "USEREMAIL_USERUSERNAME" VARCHAR2(32) NOT NULL ENABLE,  
	     CONSTRAINT "USEREMAIL_CON" PRIMARY KEY ("USEREMAIL_EMAILACCOUNT", "USEREMAIL_USERUSERNAME") ENABLE, 
	       CONSTRAINT "USEREMAIL_FK" FOREIGN KEY ("USEREMAIL_USERUSERNAME") 
	      REFERENCES  "USERS" ("USERS_USERNAME") ON DELETE CASCADE ENABLE 
	   ) ; 


CREATE TABLE  "USERS"  
   (    "USERS_USERNAME" VARCHAR2(64) NOT NULL ENABLE,  
	    "USERS_FIRSTNAME" VARCHAR2(64),  
	    "USERS_SECONDNAME" VARCHAR2(64),  
	    "USERS_PROFILEPHOTO" VARCHAR2(64) DEFAULT 'NO',  
	    "USERS_CITY" VARCHAR2(64),  
	    "USERS_STREET" VARCHAR2(64),  
	    "USERS_ZIP" VARCHAR2(64),  
	    "USERS_FAVTRACK" VARCHAR2(64),  
	    "USERS_FAVARTIST" VARCHAR2(64),  
	    "USERS_FAVGENRE" VARCHAR2(64),  
	    "USERS_NUMBERPURCHASES" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	    "USERS_MONEYBALANCE" NUMBER DEFAULT 0 NOT NULL ENABLE,  
	    "USERS_CARTID" NUMBER NOT NULL ENABLE,  
	     CONSTRAINT "USERS_PK" PRIMARY KEY ("USERS_USERNAME") ENABLE, 
	     CONSTRAINT "CK_USERS_NUMBERPURCHASES" CHECK ("USERS_NUMBERPURCHASES">=0) ENABLE, 
	     CONSTRAINT "CK_USERS_PROFILEPHOTO" CHECK ("USERS_PROFILEPHOTO" LIKE '[SI, NO]' ) ENABLE, 
	       CONSTRAINT "USERS_CON" FOREIGN KEY ("USERS_CARTID") 
	      REFERENCES  "PURCHASE_TRACKS" ("PURCHASE_TRACKS_CARTID") ENABLE 
	     
	   ) ; 


CREATE TABLE  "USERTRACK"  
   (    "USERTRACK_USERNAME" VARCHAR2(64) NOT NULL ENABLE,  
	    "USERTRACK_TRACKREFERENCENUMBER" NUMBER NOT NULL ENABLE,  
	     CONSTRAINT "USERTRACK_CON" PRIMARY KEY ("USERTRACK_USERNAME", "USERTRACK_TRACKREFERENCENUMBER") ENABLE, 
	       CONSTRAINT "USERTRACK_CONS" FOREIGN KEY ("USERTRACK_USERNAME") 
	      REFERENCES  "USERS" ("USERS_USERNAME") ENABLE, 
	       CONSTRAINT "USERTRACK_CONST" FOREIGN KEY ("USERTRACK_TRACKREFERENCENUMBER") 
	      REFERENCES  "TRACKS" ("TRACKS_REFERENCENUMBER") ENABLE 
	   ) ; 



CREATE TABLE  "USER_AUDIOPREF"  
   (    "USER_AUDIOPREF_PROFILEPREF" VARCHAR2(64) NOT NULL ENABLE,  
	    "USER_AUDIOPREF_USERNAME" VARCHAR2(64) NOT NULL ENABLE,  
	     CONSTRAINT "USER_AUDIOPREF_CON" PRIMARY KEY ("USER_AUDIOPREF_PROFILEPREF", "USER_AUDIOPREF_USERNAME") ENABLE, 
	       CONSTRAINT "USER_AUDIOPREF_FK" FOREIGN KEY ("USER_AUDIOPREF_USERNAME") 
	      REFERENCES  "USERS" ("USERS_USERNAME") ON DELETE CASCADE ENABLE 
	   ) ;​ 